### ISSUE TITLE
Did you know about posh-git and posh-hg?

### ISSUE THREAD

**Issue by PProvost** [shanselman/PowerShellHgGit#1]
Hey Scott,

Saw you push this up and wasn't sure if you knew about these projects that do very similar things. I've been quite happy with them.

https://github.com/dahlbyk/posh-git
https://github.com/JeremySkinner/posh-hg
https://github.com/JeremySkinner/posh-svn

They are quite nice to integrate into your prompt, etc. Check my dotfiles repo to see how.

--Peter

**Comment by shanselman** [comment]
My thing is their thing. We are working together.

## 

Scott Hanselman

**Comment by PProvost** [comment]
It wasn't a fork of theirs (or vice versa) so it was a bit confusing. Why not just fork the others if it is the same? :)

**Comment by andhernand** [comment]
@PProvost: http://www.hanselman.com/blog/PromptsAndDirectoriesEvenBetterGitAndMercurialWithPowerShell.aspx

**Comment by PProvost** [comment]
Interesting. That is precicely NOT what I want. I'm old-school UNIX style. Single-purpose, modular, small things that do exactly what I want. Don't bundle things together that are different. That's why they are different. Posh-git, Posh-Hg and Posh-Svn live perfectly nicely together and this way I get to choose which I want and when.

**Comment by shanselman** [comment]
They in fact _didn't_ work together (their prompts) until just recently when we worked together to make them work together.

## 

Scott Hanselman

**Comment by PProvost** [comment]
Coolio. BTW, once I saw that work, I put it into Posh-Svn as well, and have all three modules working nicely together in my prompt. :)
